name: Test CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: cache jest
      uses: actions/cache@v3
      with:
        path: node_modules/.cache/jest
        key: jest-v1-${hashFiles('package-lock.json')}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
            jest-v1-

    - name: Get number of CPU cores
      id: cpu-cores
      uses: SimenB/github-actions-cpu-cores@v2

    - name: Run Jest tests
      run: npx jest  --max-workers ${{ steps.cpu-cores.outputs.count }}
